from datetime import date as date_type


def generate_brief(data: dict) -> str:
    today = date_type.today().strftime("%d %b %Y")
    return f"""# Experiment Brief: {data.get('name', 'Untitled')}

**Owner:** {data.get('owner', '—')} | **Created:** {today} | **Status:** {data.get('status', 'Planned').title()}

---

## Hypothesis
{data.get('hypothesis', '—')}

## Variants
- **Control (A):** {data.get('control_description', '—')}
- **Variant (B):** {data.get('variant_description', '—')}

## Metrics
- **Primary:** {data.get('primary_metric', '—')}
- **Secondary:** {data.get('secondary_metrics', '—') or 'None'}

## Sample Size & Timeline
- **Required sample:** {data.get('sample_size_per_variant', '—'):,} per variant (set in Step 1)
- **Start date:** {data.get('start_date', '—')}
- **Expected end date:** {data.get('end_date', '—')}

## Risks & Assumptions
{data.get('risks', '—') or 'None documented.'}

## Notes
{data.get('notes', '') or '—'}

---
*Generated by A/B Testing Framework*
"""


def generate_results_doc(data: dict) -> str:
    return f"""# Experiment Results: {data.get('name', 'Untitled')}

**Owner:** {data.get('owner', '—')} | **Period:** {data.get('start_date', '—')} → {data.get('end_date', '—')} | **Decision:** {data.get('decision', '—')}

---

## Summary
{data.get('summary', '—')}

## Observed Results
| Metric | Control | Variant | Lift | Significant? |
|--------|---------|---------|------|-------------|
| {data.get('primary_metric', 'Primary')} | {data.get('control_rate', '—')} | {data.get('variant_rate', '—')} | {data.get('absolute_lift', '—')} | {data.get('significant', '—')} |

## Statistical Analysis
- **p-value:** {data.get('p_value', '—')}
- **Pre-committed MDE:** {data.get('mde', '—')}
- **MDE met:** {data.get('mde_met', '—')}
- **Test type:** {data.get('test_type', '—')}

## Decision & Rationale
**{data.get('decision', '—')}**

{data.get('decision_rationale', '—')}

## Learnings
{data.get('learnings', '—') or 'None documented.'}

## Next Steps
{data.get('next_steps', '—') or 'None documented.'}

---
*Generated by A/B Testing Framework*
"""


BRIEF_TEMPLATE = """\
# Experiment Brief: [Experiment Name]

**Owner:** [Name] | **Created:** [Date] | **Status:** Planned

---

## Hypothesis
If we [change X], then [metric Y] will [increase/decrease] by [Z%] because [reason].

## Variants
- **Control (A):** [What users currently see / experience]
- **Variant (B):** [What the variant changes]

## Metrics
- **Primary:** [The one metric that decides if we ship]
- **Secondary:** [Supporting metrics to watch]

## Sample Size & Timeline
- **Required sample:** [N] per variant
- **Start date:** [YYYY-MM-DD]
- **Expected end date:** [YYYY-MM-DD]

## Risks & Assumptions
- [Assumption 1]
- [Risk 1]

## Notes
[Any other context — stakeholders, related experiments, constraints]

---
*Template from A/B Testing Framework*
"""

RESULTS_TEMPLATE = """\
# Experiment Results: [Experiment Name]

**Owner:** [Name] | **Period:** [Start] → [End] | **Decision:** [SHIP / DO NOT SHIP / INCONCLUSIVE]

---

## Summary
[1–2 sentence plain-English summary of what happened.]

## Observed Results
| Metric | Control | Variant | Lift | Significant? |
|--------|---------|---------|------|-------------|
| [Primary metric] | [X%] | [Y%] | [+Z%] | Yes / No |

## Statistical Analysis
- **p-value:** [0.000]
- **Pre-committed MDE:** [X%]
- **MDE met:** Yes / No
- **Test type:** Two-sided / One-sided

## Decision & Rationale
**[SHIP / DO NOT SHIP / INCONCLUSIVE]**

[Why you made this decision, referencing the MDE and p-value.]

## Learnings
- [What you learned about user behaviour]
- [What surprised you]

## Next Steps
- [Follow-up experiment ideas]
- [What to monitor post-ship]

---
*Template from A/B Testing Framework*
"""
